package biz.spfsolutions.ima.service.payment;

public enum PaymentModeEnum {
	AUTHORIZE_PAYMENT,
	MERCURY_PAYMENT, 
	ENTER_AT_CHECKOUT_PAYMENT_AUTH, 
	ENTER_AT_CHECKOUT_PAYMENT_MERCURY,
	PAY_AT_PICKUP_PAYMENT,
	ENTER_AT_CHECKOUT_PAYMENT_UNSPECIFIED
}
